In [1]:
import pandas as pd

In [5]:
# \Users\dpuse\OneDrive\Documentos\datascience-g8
ventas_df = pd.read_csv(
    r"C:\Users\dpuse\OneDrive\Documentos\datascience-g8\ventas.csv",
    dtype={"precio_unitario": "float64"}
)

In [7]:
ventas_df.head(10)

,fecha,region,vendedor,producto,categoria,unidades,precio_unitario,descuento
0,2024-01-02,Oeste,Pedro Diaz,Auriculares,Accesorios,5,130.0,0.0
1,2024-01-02,Sur,Luis Gomez,Monitor 27,Tecnologia,14,320.0,0.0
2,2024-01-02,Centro,Carlos Vega,Silla Ergo,Mobiliario,1,280.0,0.0
3,2024-01-02,Centro,Pedro Diaz,Laptop Pro,Tecnologia,10,1200.0,0.0
4,2024-01-03,Sur,Elena Mora,Auriculares,Accesorios,2,130.0,0.1
5,2024-01-03,Oeste,Javier Sanz,Escritorio,Mobiliario,2,450.0,0.0
6,2024-01-03,Norte,Carlos Vega,Silla Ergo,Mobiliario,4,280.0,0.0
7,2024-01-03,Norte,Sofia Leon,Silla Ergo,Mobiliario,1,280.0,0.0
8,2024-01-03,Centro,Carlos Vega,Laptop Pro,Tecnologia,1,1200.0,0.1
9,2024-01-03,Centro,Pedro Diaz,Escritorio,Mobiliario,2,450.0,0.0

In [9]:
mascara = ventas_df["region"] == "Sur"
ventas_sur = ventas_df[mascara]
ventas_sur.tail()

,fecha,region,vendedor,producto,categoria,unidades,precio_unitario,descuento
1156,2024-12-17,Sur,Luis Gomez,Teclado Mec,Accesorios,11,95.0,0.15
1163,2024-12-19,Sur,Luis Gomez,Silla Ergo,Mobiliario,2,280.0,0.00
1181,2024-12-25,Sur,Ana Torres,Tablet Air,Tecnologia,14,640.0,0.00
1191,2024-12-30,Sur,Luis Gomez,Silla Ergo,Mobiliario,3,280.0,0.00
1192,2024-12-30,Sur,Javier Sanz,Teclado Mec,Accesorios,8,95.0,0.10

In [11]:
ventas_sur = ventas_df[ventas_df["region"] == "Sur"]

ventas_sur

,fecha,region,vendedor,producto,categoria,unidades,precio_unitario,descuento
1,2024-01-02,Sur,Luis Gomez,Monitor 27,Tecnologia,14,320.0,0.00
4,2024-01-03,Sur,Elena Mora,Auriculares,Accesorios,2,130.0,0.10
14,2024-01-05,Sur,Pedro Diaz,Teclado Mec,Accesorios,12,95.0,0.05
21,2024-01-07,Sur,Marta Ruiz,Auriculares,Accesorios,4,130.0,0.10
22,2024-01-08,Sur,Elena Mora,Teclado Mec,Accesorios,3,95.0,0.00
...,...,...,...,...,...,...,...,...
1156,2024-12-17,Sur,Luis Gomez,Teclado Mec,Accesorios,11,95.0,0.15
1163,2024-12-19,Sur,Luis Gomez,Silla Ergo,Mobiliario,2,280.0,0.00
1181,2024-12-25,Sur,Ana Torres,Tablet Air,Tecnologia,14,640.0,0.00
1191,2024-12-30,Sur,Luis Gomez,Silla Ergo,Mobiliario,3,280.0,0.00
1192,2024-12-30,Sur,Javier Sanz,Teclado Mec,Accesorios,8,95.0,0.10

In [14]:
ventas_df[(ventas_df["region"] == "Sur") | (ventas_df["region"] == "Norte")]

,fecha,region,vendedor,producto,categoria,unidades,precio_unitario,descuento
1,2024-01-02,Sur,Luis Gomez,Monitor 27,Tecnologia,14,320.0,0.0
4,2024-01-03,Sur,Elena Mora,Auriculares,Accesorios,2,130.0,0.1
6,2024-01-03,Norte,Carlos Vega,Silla Ergo,Mobiliario,4,280.0,0.0
7,2024-01-03,Norte,Sofia Leon,Silla Ergo,Mobiliario,1,280.0,0.0
10,2024-01-04,Norte,Sofia Leon,Monitor 27,Tecnologia,3,320.0,0.1
...,...,...,...,...,...,...,...,...
1191,2024-12-30,Sur,Luis Gomez,Silla Ergo,Mobiliario,3,280.0,0.0
1192,2024-12-30,Sur,Javier Sanz,Teclado Mec,Accesorios,8,95.0,0.1
1194,2024-12-30,Norte,Ana Torres,Tablet Air,Tecnologia,4,640.0,0.0
1198,2024-12-31,Norte,Ana Torres,Monitor 27,Tecnologia,6,320.0,0.0
1199,2024-12-31,Norte,Marta Ruiz,Raton Ergo,Accesorios,8,45.0,0.0

In [15]:
ventas_df.head(10)

,fecha,region,vendedor,producto,categoria,unidades,precio_unitario,descuento
0,2024-01-02,Oeste,Pedro Diaz,Auriculares,Accesorios,5,130.0,0.0
1,2024-01-02,Sur,Luis Gomez,Monitor 27,Tecnologia,14,320.0,0.0
2,2024-01-02,Centro,Carlos Vega,Silla Ergo,Mobiliario,1,280.0,0.0
3,2024-01-02,Centro,Pedro Diaz,Laptop Pro,Tecnologia,10,1200.0,0.0
4,2024-01-03,Sur,Elena Mora,Auriculares,Accesorios,2,130.0,0.1
5,2024-01-03,Oeste,Javier Sanz,Escritorio,Mobiliario,2,450.0,0.0
6,2024-01-03,Norte,Carlos Vega,Silla Ergo,Mobiliario,4,280.0,0.0
7,2024-01-03,Norte,Sofia Leon,Silla Ergo,Mobiliario,1,280.0,0.0
8,2024-01-03,Centro,Carlos Vega,Laptop Pro,Tecnologia,1,1200.0,0.1
9,2024-01-03,Centro,Pedro Diaz,Escritorio,Mobiliario,2,450.0,0.0

In [16]:
df_filtrado = ventas_df[ventas_df["precio_unitario"].between(90, 200)]
df_filtrado

,fecha,region,vendedor,producto,categoria,unidades,precio_unitario,descuento
0,2024-01-02,Oeste,Pedro Diaz,Auriculares,Accesorios,5,130.0,0.00
4,2024-01-03,Sur,Elena Mora,Auriculares,Accesorios,2,130.0,0.10
13,2024-01-05,Norte,Sofia Leon,Auriculares,Accesorios,11,130.0,0.00
14,2024-01-05,Sur,Pedro Diaz,Teclado Mec,Accesorios,12,95.0,0.05
18,2024-01-06,Oeste,Carlos Vega,Auriculares,Accesorios,2,130.0,0.10
...,...,...,...,...,...,...,...,...
1173,2024-12-22,Norte,Marta Ruiz,Teclado Mec,Accesorios,12,95.0,0.05
1177,2024-12-24,Oeste,Ana Torres,Auriculares,Accesorios,11,130.0,0.00
1183,2024-12-26,Centro,Luis Gomez,Auriculares,Accesorios,6,130.0,0.00
1189,2024-12-29,Oeste,Javier Sanz,Auriculares,Accesorios,6,130.0,0.00
1192,2024-12-30,Sur,Javier Sanz,Teclado Mec,Accesorios,8,95.0,0.10

In [18]:
(ventas_df["region"]) == "Centro"

0       False
1       False
2        True
3        True
4       False
        ...
1195    False
1196    False
1197    False
1198    False
1199    False
Name: region, Length: 1200, dtype: bool

In [21]:
len(ventas_df[(ventas_df["categoria"] == "Tecnología") & (ventas_df["unidades"] > 10)])

0

In [22]:
ventas_df[ventas_df["descuento"] > 0]

,fecha,region,vendedor,producto,categoria,unidades,precio_unitario,descuento
4,2024-01-03,Sur,Elena Mora,Auriculares,Accesorios,2,130.0,0.10
8,2024-01-03,Centro,Carlos Vega,Laptop Pro,Tecnologia,1,1200.0,0.10
10,2024-01-04,Norte,Sofia Leon,Monitor 27,Tecnologia,3,320.0,0.10
11,2024-01-04,Oeste,Pedro Diaz,Escritorio,Mobiliario,10,450.0,0.05
12,2024-01-04,Centro,Marta Ruiz,Tablet Air,Tecnologia,2,640.0,0.15
...,...,...,...,...,...,...,...,...
1187,2024-12-28,Este,Ana Torres,Raton Ergo,Accesorios,8,45.0,0.05
1190,2024-12-29,Centro,Luis Gomez,Laptop Pro,Tecnologia,1,1200.0,0.10
1192,2024-12-30,Sur,Javier Sanz,Teclado Mec,Accesorios,8,95.0,0.10
1196,2024-12-30,Este,Marta Ruiz,Laptop Pro,Tecnologia,13,1200.0,0.05
1197,2024-12-31,Oeste,Ana Torres,Monitor 27,Tecnologia,2,320.0,0.05